help_table = [
    ["", "", "Hello, you can use the following commands with the given format:", "", ""],
    ["Command", "param first", "param second", "param third", "Description"],
    ["help", "", "", "", "Display this help message"],
    ["hello", "", "", "", "Greet the bot"],
    ["add", "<user_name>", "<phone>", "[birthday]", "Add a user to the address book"],
    ["change", "<user_name>", "<phone_to_change>", "<phone_to_change_to>", "Change a phone number"],
    ["show-all", "", "", "", "Show all records in a table"],
    ["goodbye/close/exit", "", "", "", "Exit the application"],
    ["find", "<some_letters>", "<some_numbers>", "", "Find a record by name or phone"],
    ["delete-phone", "<user_name>", "<phone>", "", "Greet the bot"],
    ["delete-user", "<user_name>", "", "", "Delete a user from the address book"],
    ["next-birthday", "<user_name>", "", "", "When the user's birthday is"],
    ["", "", "Variation format for telephone number:", "", ""],
    ["+38(055)111-22-33", "", "", "", "", ""],
    ["38(055)111-22-34", "", "", "", "", ""],
    ["8(055)111-22-35", "", "", "", "", ""],
    ["(055)111-22-36", "", "", "", "", ""],
    ["055111-22-37", "", "", "", "", ""],
    ["and all variants without \"-\"", "", "", "", "", ""],
]